<?php
    
namespace app\admin\common;

use app\admin\model\Systems;
use think\Controller;
class Base extends Controller{

   protected function _initialize()
   {

       $controller = request()->controller();
      // halt($controller);
        if ($controller != "Login" && $controller != "Captcha"){
            if (!session('uid')){
                $this->error('请先登录');
            }
        }


       parent::_initialize(); // TODO: Change the autogenerated stub
   }


   public function setSystem(){

       $system = Systems::all()->toArray();

       $configArr=null;

       foreach ($system as $k=>$v){

            $configArr[$v['name']] = $v['value'];

       }

       return $configArr;

   }

}



